name: saveme
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.6
  firebase_auth: ^3.4.1
  firebase_core: ^1.19.1
  fluttertoast: ^8.0.9
  google_maps_flutter: ^2.1.8
  flutter_polyline_points: ^1.0.0
  geolocator: ^7.3.0
  flutter_google_places: ^0.3.0
  geocoder2: ^1.1.2
  http: ^0.13.3
  google_maps_webservice: ^0.0.19
  google_place: ^0.4.7
  custom_info_window: ^1.0.1
  cloud_firestore: ^3.3.0
  provider: ^6.0.3



  cupertino_icons: ^1.0.2

dev_dependencies:
  icons_launcher: ^1.0.0
  change_app_package_name: ^1.1.0
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: 'assets/icon/icon.png'
  ios: true
  android: true

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icon/
    - assets/screens/signin/
    - assets/screens/register/
    - assets/screens/add_post/
  fonts:
    - family: OoohBaby
      fonts:
        - asset: assets/fonts/OoohBaby-Regular.ttf

  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
